import Image from 'next/image';
import Navbar from '../components/Navbar';

// Gallery images with their actual hashes from Figma
const galleryImages = [
  '/images/gallery-01.png', // hash: 289bb7c3...
  '/images/gallery-02.png', // hash: fed704d9...
  '/images/gallery-03.png', // hash: d31c4c42...
  '/images/gallery-04.png', // hash: 1c0d381a...
  '/images/gallery-05.png', // hash: 46024272...
  '/images/gallery-06.png', // hash: 289bb7c3...
  '/images/gallery-07.png', // hash: 4c77783a...
  '/images/gallery-08.png', // hash: 5cd75a9e...
  '/images/gallery-09.png', // hash: e519d570...
  '/images/gallery-10.png', // hash: 3a0cad5b...
  '/images/gallery-11.png', // hash: 289bb7c3...
  '/images/gallery-12.png', // hash: 5260029b...
  '/images/gallery-13.png', // hash: 626a0810...
  '/images/gallery-14.png', // hash: 15467c65...
  '/images/gallery-15.png', // hash: be02c8b9...
  '/images/gallery-16.png', // hash: e48dff4e...
  '/images/gallery-17.png', // hash: 01ef5a9c...
  '/images/gallery-18.png', // hash: 5cd75a9e...
  '/images/gallery-19.png', // hash: e48dff4e...
  '/images/gallery-20.png', // hash: 86118f80...
  '/images/gallery-21.png', // hash: 9a8bd22b...
  '/images/gallery-22.png', // hash: e48dff4e...
  '/images/gallery-23.png', // hash: 01ef5a9c...
  '/images/gallery-24.png', // hash: a4ca245f...
];

export default function GalleryPage() {
  return (
    <div className="bg-white min-h-screen">
      <Navbar />

      {/* Gallery Grid */}
      <main className="flex justify-center pb-20 px-4 md:px-0">
        <div
          className="grid gap-[11px] md:gap-[21px]"
          style={{
            gridTemplateColumns: 'repeat(3, 1fr)',
            maxWidth: '906px',
            width: '100%',
          }}
        >
          {galleryImages.map((src, index) => (
            <div
              key={index}
              className="gallery-img relative overflow-hidden bg-[#ededed] cursor-pointer"
              style={{ aspectRatio: '288/210' }}
            >
              <Image
                src={src}
                alt={`Gallery image ${index + 1}`}
                fill
                className="object-cover"
                sizes="(max-width: 768px) 30vw, 288px"
              />
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
